onlyBuiltDependencies:
  - esbuild
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  next@>=16.1.0-canary.0 <16.1.0-canary.17: '>=16.1.0-canary.17'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  ajv@<8.18.0: '>=8.18.0'
